artifact_location: file:///E:/MLopes/Capstone-Project/mlflow_tracking_uri/468326953662665177
creation_time: 1771678054599
experiment_id: '468326953662665177'
last_update_time: 1771678054599
lifecycle_stage: active
name: LoR Hyperparameter Tuning
workspace: default
