artifact_uri: file:///E:/MLopes/Capstone-Project/mlflow_tracking_uri/468326953662665177/77310dc1d65b44e8ab922687f79a7a8a/artifacts
end_time: 1771678074990
entry_point_name: ''
experiment_id: '468326953662665177'
lifecycle_stage: active
run_id: 77310dc1d65b44e8ab922687f79a7a8a
run_name: 'LR with params: {''C'': 10, ''penalty'': ''l2'', ''solver'': ''liblinear''}'
source_name: ''
source_type: 4
source_version: ''
start_time: 1771678074733
status: 3
tags: []
user_id: malojighorpade
